### ISSUE TITLE
Python 3.5 issue

### ISSUE THREAD

**Issue by Quantumke** [lipisha/lipisha-python-client#1]
Hi,
I tried to port my system to python 3.5 and am stuck with the error :

**> POST data should be bytes or an iterable of bytes. It cannot be of type str.** 
when i execute any command such as
**> lipisha.confirm_transaction(transaction='YYYE9WWWW0')**
any help would really be appreciated.

**Comment by bmurithi** [comment]
Thanks for reporting this. Kindly try the new release on Github or pypi.
